version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: "14.15"
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: API Build
          command: |
            npm run api:build

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "14.15"
      - aws-cli/setup
      - run:
          name: Create application version package
          command: zip -r Archive.zip .
      - run:
          name: Upload package to S3
          command: aws s3 cp app.zip s3://udacity-bucket-01/Archive.zip
      - run:
          name: Create application version in Elastic Beanstalk
          command: |
            aws elasticbeanstalk create-application-version --application-name your-application-name --version-label app-$(date +%Y%m%d_%H%M%S) --source-bundle S3Bucket=arn:aws:s3:::udacity-bucket-01,S3Key=Archive.zip
      - run:
          name: Deploy App to Elastic Beanstalk
          command: |
            aws elasticbeanstalk update-environment --environment-name your-environment-name --version-label app-$(date +%Y%m%d_%H%M%S)

workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
